# Generated by Django 4.2 on 2024-12-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_unit_options_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товары'},
        ),
    ]
